### ISSUE TITLE
False positive - mass assignment where there is none

### ISSUE THREAD

**Issue by JasonBarnabe** [presidentbeef/brakeman#1001]
```ruby
	def current_url_with_params(p={})
		r = params.except(:only_path, :protocol, :host, :subdomain, :domain, :tld_length, :subdomain, :port, :anchor, :trailing_slash, :script_name, :controller, :action, :format).merge(p)
		r.permit!
		return url_for(r)
	end
```
gives "Parameters should be whitelisted for mass assignment". There's no mass assignment here!

**Comment by presidentbeef** [comment]
Hi Jason,

Brakeman warns about any use of `params.permit!` as it is a dangerous pattern. In this case, a medium confidence warning because it didn't see any mass assignment. If it did see a subsequent mass assignment, it would be high confidence.

This is a bit of an unusual use of `permit!`. Does it even have any effect in this case?

**Comment by JasonBarnabe** [comment]
Without it, it's `Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.`

**Comment by presidentbeef** [comment]
I'm afraid it's too difficult to tell that `r.permit!` is never used for mass assignment. That's why Brakeman always warns about uses of `permit!` just in case.
