### ISSUE TITLE
Syntax error, unexpected tIDENTIFIER, expecting kDO or '{' or '(' (SyntaxError)

### ISSUE THREAD

**Issue by jonaslimafleck** [presidentbeef/brakeman#1016]
When running Brakeman 3.5.0 scanner in Microsoft Windows 10 64 bits with Ruby 1.8.7 the terminal outputs the following syntax error:

Loading scanner...
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman/processors/alias_processor.rb:566: syntax error, unexpected tIDENTIFIER, expecting kDO or '{' or '(' (SyntaxError)
    condition = exp.condition = process exp.condition
                                           ^
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman/processor.rb:2
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman/processor.rb:2:in `each'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman/processor.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman/scanner.rb:5
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman.rb:346:in `scan'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/../lib/brakeman.rb:69:in `run'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/brakeman-3.5.0/bin/brakeman:86
        from C:/Ruby187/bin/brakeman:19:in `load'
        from C:/Ruby187/bin/brakeman:19

**Comment by presidentbeef** [comment]
Hi Jonas,

Brakeman has not supported *running* on Ruby 1.8.7 since [Brakeman 3.1.0](http://brakemanscanner.org/blog/2015/08/30/brakeman-3-dot-1-0-released/). You can still scan code *written* with 1.8.7 syntax, but you will need at least Ruby 1.9.3 to run Brakeman.

Please note Ruby 1.8.7 has been unmaintained [since June 2013](https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) and Ruby 1.9.3 [since February 2015](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/).
