### ISSUE TITLE
3.7.0 failing on CI with cannot load such file -- erubis

### ISSUE THREAD

**Issue by sonalkr132** [presidentbeef/brakeman#1068]
I am using following to run brakeman on Travis:
```yml
script:
  - script/brakeman
```

Yesterday, our [build broke](https://travis-ci.org/rubygems/rubygems.org/jobs/248939728#L1103) after brakeman 3.7.0 was released with:
```
Parsing files...
cannot load such file -- erubis
Please install the appropriate dependency: erubis.
```

I am not able to reproduce this locally even after I uninstall erubis from my system. Any kind of help would be nice :pray:

**Comment by presidentbeef** [comment]
Hi Aditya,

The reason this changed is because the [`brakeman.yml`](https://github.com/rubygems/rubygems.org/blob/3ea2ba8567317ae91590869b939b6a09fd13be49/config/brakeman.yml#L10) file sets `:rails4: true`. Prior to Brakeman 3.7.0, this did not work correctly. (If you run `brakeman -C --rails4`, you will see it actually sets `:rails4: true` _and_ `:rails3: true` which is what is required internally.) That meant templates were being rendered with ERB instead of erubis like they should have been.

Because rubygems.org is using [`brakeman-min`](https://github.com/rubygems/rubygems.org/blob/3ea2ba8567317ae91590869b939b6a09fd13be49/script/brakeman#L4), dependencies must be explicitly installed.

So [this script](https://github.com/rubygems/rubygems.org/blob/3ea2ba8567317ae91590869b939b6a09fd13be49/script/brakeman) needs to install `erubis`.

**Comment by presidentbeef** [comment]
Also `:rails4: true` should be removed from `brakeman.yml`, since rubygems.org is using Rails 5 and Brakeman detects that automatically.

**Comment by sonalkr132** [comment]
Thank you @presidentbeef :100:
