### ISSUE TITLE
Ignore with note and  --only-file incompatible

### ISSUE THREAD

**Issue by nikolai-b** [presidentbeef/brakeman#1267]
### Background

Brakeman version: 4.3.1
Rails version: 5.2.0
Ruby version: 2.5.1

### Issue

When I ran
```
bin/brakeman -I
```

with file `app/models/bad.rb`

```
# frozen_string_literal: true
class Bad < ApplicationRecord
  scope :ordered, ->(locale) {
    name_in_locale = "name_#{locale}"
    order(name_in_locale)
  }
end
```

and ignored a warning and added a note brakeman adds to my `brakeman.ignore` file:

```
    {
      "warning_type": "SQL Injection",
      "warning_code": 0,
      "fingerprint": "283d23cbda85c80a75997a0ff3eec05fb768cd6c3ffc68293f970a39dfae056e",
      "check_name": "SQL",
      "message": "Possible SQL injection",
      "file": "app/models/bad.rb",
      "line": 5,
      "link": "https://brakemanscanner.org/docs/warning_types/sql_injection/",
      "code": "order(\"name_#{locale}\")",
      "render_path": null,
      "location": {
        "type": "method",
        "class": "Bad",
        "method": "ordered"
      },
      "user_input": "locale",
      "confidence": "Medium",
      "note": "add note"
    }
```

but then if I run

```
bin/brakeman --only-file app/models/bad.rb -I
```

the warning is not ignored!  If I ignore it again then brakeman adds:

```
    {
      "warning_type": "SQL Injection",
      "warning_code": 0,
      "fingerprint": "f70878ca6eb2404d61bafb615f78610a77ad3f8800c4531d90409087e145d11c",
      "check_name": "SQL",
      "message": "Possible SQL injection",
      "file": "app/models/bad.rb",
      "line": 5,
      "link": "https://brakemanscanner.org/docs/warning_types/sql_injection/",
      "code": "order(\"name_#{locale}\")",
      "render_path": null,
      "location": {
        "type": "method",
        "class": "Bad",
        "method": null
      },
      "user_input": "locale",
      "confidence": "Medium",
      "note": ""
    },
```

to my `brakeman.ignore`

**Comment by presidentbeef** [comment]
Hi Nikolai,

Thank you for reporting this issue.

Short answer: don't use `--only-files` 😃 

The difference in the two warnings is the location. In one the method is `null`, in the other it's `ordered`.

Here is what is happening: `scope` calls are only processed correctly for Rails 3.1.0 and newer. If you run Brakeman with `--only-files` and don't provide enough files to determine the version of Rails in use (e.g. `Gemfile`) then it won't process the `scope` call properly.

The code that handles named scopes is pretty old. I've moved away from worrying about whether a feature should or should not be available in the version of Rails being used. (This is because applications may be backporting new features to old versions or porting old features to new versions.) So, probably this version-specific behavior should be removed.

However, just as a warning, you will likely run into other weird issues using `--only-files`. I regret its inclusion. The intent of the option is for cases where `--skip-files` would be too tedious. Brakeman really needs to have visibility into the entire application to work properly. It is not a per-file scanner.

**Comment by nikolai-b** [comment]
@presidentbeef this is the code in https://github.com/prontolabs/pronto-brakeman/blob/d3de48397e9415d732c09618adacb99382648944/lib/pronto/brakeman.rb#L15 
If pronto-brakeman passed in the `app_path` would that help fix this?


P.S.
Out of curiosity I'm a bit lost as to how e4f76d9 fixes this...

**Comment by presidentbeef** [comment]
I don't recommend using Pronto, for this reason.

As for e4f76d9 - sorry, tagged the wrong issue!

**Comment by presidentbeef** [comment]
Finally followed up with my comment
> So, probably this version-specific behavior should be removed.
with #1435
