### ISSUE TITLE
Potentially dangerous key allowed for mass assignment

### ISSUE THREAD

**Issue by garimachhabra20** [presidentbeef/brakeman#1269]
### Background

Brakeman version: 4.3
Rails version: 4.2.8
Ruby version: 2.3.4

Link to Rails application code: ?
#### False Positive

*Full* warning from Brakeman: Potentially dangerous key allowed for mass assignment

Relevant code:

```
  def user_params
    params.require(:user).permit(:admin)
  end
```

As per document - 
https://brakemanscanner.org/docs/warning_types/mass_assignment/ suggests that the recommended way is to use "permit" to avoiding saving all the fields in database directly. But I have used the same in my code but Brakeman still warns me with message " Potentially dangerous key allowed for mass assignment"

**Comment by presidentbeef** [comment]
Hi @garimachhabra20,

I am sensing some confusion here.

Assuming you have some code like:

```ruby
User.create(user_params)
```

Then an attacker could use a request like

```
?user[:admin]=true
```

To make themselves an administrator.

`permit` is a whitelist of *allowed* keys. Brakeman is warning about `permit(:admin)` because that is very likely a security issue.

See here for more information: https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters

I am open to suggestions for making the Brakeman documentation clearer.

**Comment by garimachhabra20** [comment]
@presidentbeef Our requirement is  just to update "admin" permissions for a user. How do you suggest we do that.

**Comment by presidentbeef** [comment]
If it's intentional, then you can [ignore the warning](https://brakemanscanner.org/docs/ignoring_false_positives/).

I would suggest you only call `permit(:admin)` in the action where you need it, though, instead of in a helper method that may be re-used in places you do not intend.

**Comment by garimachhabra20** [comment]
Thanks. This method is there only in controller class.
