### ISSUE TITLE
Check cookies_serializer option in rails

### ISSUE THREAD

**Issue by korrs** [presidentbeef/brakeman#1316]
Rails apps can use insecure serialization for cookies, that uses marshalling! This vulnerability still has a high risk and i think brakeman should notify us about this problem. 

I suggest to add check which would read rails option(```Rails.application.config.action_dispatch.cookies_serializer```) and would show a warning if option is equal to ```:marshal```. I can make pr if this kind of check possible to add in a brakeman.

**Comment by presidentbeef** [comment]
Hi @korrs - seems like a good idea.

Is the premise that using marshalled cookies allows an attacker to send malicious cookies that may execute code when deserialized? Do you have a proof of concept, or is it just theoretically a problem?

**Comment by korrs** [comment]
I read about it from [this](https://robertheaton.com/2013/07/22/how-to-hack-a-rails-app-using-its-secret-token/) article

**Comment by presidentbeef** [comment]
Thank you for the link. However, that article is about generating session cookies via leaked secret tokens - I don't think it matters what serialization technique is used.

**Comment by korrs** [comment]
Why does it's not matter? Maybe exists another vectors for attacks if you have a secret token but this vulnerability possible to use too).

**Comment by presidentbeef** [comment]
How does changing the serialization to JSON address the issue raised in that article?

**Comment by korrs** [comment]
@presidentbeef, you mean that ActiveSupport::JSON not rescue from this attack and this deserialization method not safe too?

**Comment by korrs** [comment]
I look at [implementaion](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/json/decoding.rb#L22) of decoding in ActiveSupport::tJSON(which [used](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/cookies.rb#L551) for deserealizing of cookies if json option selected) and i can't see how possible to execute this attack.

**Comment by presidentbeef** [comment]
So my thought here is we _should_ warn about using Marshal for serializing cookies.

The blog post just threw me off because it was more about stealing secret keys, which becomes more dangerous if the application uses Marshal for session cookies or any encrypted cookie, really. The problem in the original request is actually broader than that, and I thought perhaps someone had posted about a generic attack using any cookie using Marshal.

**Comment by gingerlime** [comment]
Sorry for barging in, but we were having some trouble applying this setting and not using `:hybrid` and I wanted to check the best course of action ... 

First of all, just to make sure I get things straight, this is really a "defense-in-depth" scenario, right? because if someone has access to your secret keys, then lots of bad stuff can happen. (I agree that remote code execution would be particularly bad when your keys get compromised).

Implementing this change however going straight from `:marshal` to `:json` seems to lead to this error

`JSON::ParserError unexpected token at [iI"**************;'` 

and then the user gets a 500, and retrying won't help either (the cookie has an old marshalled data...)

I guess the only viable solution is changing `secret_key_base` and invalidating everyone's cookies, right?

**Comment by presidentbeef** [comment]
Hi @gingerlime - you are right this is a "defense-in-depth" setting. But consider CVE-2019-5418 had a bigger impact if using Marshal for cookies.
`:hybrid` is intended to help migrate from Marshal to JSON. The reason Brakeman warns about `:hybrid` is because I suspect there are applications using `:hybrid` and never switching to `:json`. So in your case, you can use `:hybird` and then when you are comfortable that existing sessions have been switched to JSON, then you can change the setting to `:json`.
Hope that helps.

**Comment by gingerlime** [comment]
Thanks for getting back to me @presidentbeef. Do you mean CVE-2019-5420 ?

Re moving to `:hybrid` and then `:json`... however long we might leave it on, there's always a chance of someone with an old cookie later on coming in. If they then get a 500 and we get noise from JSON parse errors, then it won't really help. I think we'd have to reset our `secret_key_base` sooner or later anyway. I can't think of any other solution, but perhaps you or someone else has a suggestion?
