### ISSUE TITLE
TypeError: superclass mismatch for class Ruby19Parser

### ISSUE THREAD

**Issue by chuckphillips** [presidentbeef/brakeman#1333]
### Background

Brakeman version: 4.5.0
Rails version: 5.2.2.1
Ruby version: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]

Link to Rails application code: 
https://stackoverflow.com/a/50145371

### Issue

Running Brakeman.run with options via rake throws the following error:

TypeError: superclass mismatch for class Ruby19Parser
from ruby/2.5.0/lib/ruby/gems/2.5.0/gems/brakeman-pro-4.5.0/bundle/ruby/2.4.0/gems/ruby_parser-legacy-1.0.0/lib/ruby_parser/legacy/ruby19_parser.rb:8:in `<top (required)>'

**Comment by presidentbeef** [comment]
Hi @chuckphillips,

I do not recommend running Brakeman from Rake because issues like this come up all the time.

I'm guessing your application has another dependency on `ruby_parser`. When you run Rake, every dependency is loaded (and your entire app). Somewhere an older version of `ruby_parser` (<3.13.0) is being loaded. Then Brakeman tries to use `ruby_parser-legacy` which is required for `ruby_parser` 3.13.0. Since `Ruby19Parser` is already loaded from the earlier `ruby_parser` that was loaded previously, there is a conflict.

If you want to continue using Brakeman via Rake, I would recommend trying the [`brakeman-lib`](https://rubygems.org/gems/brakeman-lib) gem instead so that dependencies will at least be explicit.

**Comment by chuckphillips** [comment]
👍 Will do. Thanks.

**Comment by chuckphillips** [comment]
Does the same apply to running the engine via specs?

```    require "brakeman/test/rspec"

    describe Brakeman do
      # Assert zero Brakeman warnings
      it "raises zero warnings" do
        expect(Brakeman::Test.run).to have_no_warnings
      end
    end
```

```.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/brakeman-pro-4.5.0/bundle/ruby/2.4.0/gems/ruby_parser-legacy-1.0.0/lib/ruby_parser/legacy/ruby19_parser.rb:8:in `<top (required)>': superclass mismatch for class Ruby19Parser (TypeError)
JSON::ParserError: An empty string is not a valid JSON string.
from .asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/brakeman-pro-4.5.0/lib/brakeman/test.rb:41:in `parse'```

**Comment by presidentbeef** [comment]
Oh...that is a pain. The test integration does attempt to solve this issue by forking prior to loading/running Brakeman, but that doesn't help if the conflicting ruby_parser version was already loaded (which it would be). The forking is intended to prevent Brakeman's dependencies from interfering with the application, but it doesn't help when the application's dependencies interfere with Brakeman :(

It may be possible to manage this in Brakeman by undefining `Ruby18Parser` and `Ruby19Parser` (maybe others) prior to loading `ruby_parser-legacy`. I'm looking into it.

**Comment by presidentbeef** [comment]
@chuckphillips - Can you try adding the following prior to requiring Brakeman?

```ruby
Object.send(:remove_const, :Ruby18Parser)
Object.send(:remove_const, :Ruby19Parser)
RubyParser.send(:remove_const, :V18)
RubyParser.send(:remove_const, :V19)
```

**Comment by chuckphillips** [comment]
That worked.
```
Brakeman::Test
  raises zero warnings

Top 1 slowest examples (6.59 seconds, 99.5% of total time):
  Brakeman::Test raises zero warnings
    6.59 seconds ./spec/lib/brakeman/test_spec.rb:8

Finished in 6.62 seconds (files took 15.32 seconds to load)
1 example, 0 failures

Randomized with seed 38536
```

**Comment by presidentbeef** [comment]
Perfect, thank you for confirming.
