### ISSUE TITLE
Is Denial of Service warning type for symbols still applicable?

### ISSUE THREAD

**Issue by Aqualon** [presidentbeef/brakeman#1373]
On https://brakemanscanner.org/docs/warning_types/denial_of_service/ you warn of Denial of Service attacks, because of `to_sym` calls on user input to controllers.

Is this still applicable with the symbol garbage collection in ruby >= 2.2?

**Comment by presidentbeef** [comment]
Correct, "Symbol DoS" does not apply to Ruby versions >= 2.2. Honestly, I don't think it was ever a really big problem for most applications anyway.

That's why the check for it is [optional and only warns on older versions of Ruby](https://github.com/presidentbeef/brakeman/blob/cf84b129f380162a9dff7f1645f0bf70c812312b/lib/brakeman/checks/check_symbol_dos.rb#L4-L12).

**Comment by Aqualon** [comment]
Thanks, should the website reflect this information?
