### ISSUE TITLE
False positive when using ViewComponent

### ISSUE THREAD

**Issue by dkniffin** [presidentbeef/brakeman#1616]
### Background

Brakeman version: 5.0.2
Rails version: 6.1.3.2
Ruby version: 2.7.3

#### False Positive

*Full* warning from Brakeman: 

```
Confidence: Weak
Category: Dynamic Render Path
Check: Render
Message: Render path contains parameter value
Code: render(action => SomeComponent.new(:foo => params[:foo])
File: app/views/something.html.slim
Line: 1
```

(I've anonymized the code here, but this should be functionally equivalent to my code)

Relevant code:

```slim
  = render SomeComponent.new(foo: params[:foo])
```

_Why might this be a false positive?_

I believe what's going on here is Brakeman is throwing an error because we have a `params` somewhere inside a call to `render`. That may have been a good check before, but it is no longer a good check now that we're using [ViewComponent](https://github.com/github/view_component). 

If I understand correctly, brakeman's goal with this check is to avoid things like `render "templates/#{params[:some_user_input]}"`, because then users could access templates they’re not supposed to. But in this case, we’re not doing that. We’re specifying the "template" via hard-coding a VC component, and it just so happens to need a param as an input.

More generally, I think this will happen more often because Rails' `render` method was updated to support [rendering any class that responds to `render_in`](https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-objects).

**Comment by kreintjes** [comment]
Hi @dkniffin it seems your issue is a duplicate of https://github.com/presidentbeef/brakeman/issues/1529 which was fixed in https://github.com/presidentbeef/brakeman/pull/1578. This isn't released yet as a new RubyGems release, but you can try it out by using the main branch of this repo (e.g. `gem 'brakeman', '~> 5.0', github: 'presidentbeef/brakeman', branch: 'main'`). Could you try if this fixes you're issue?

Ps. I ran into your issue because of slightly different problem (false positive) when `render` is used to render a collection of or single ActiveRecord object, e.g. `render User.where(id: params[:ids]).all` or `Render User.find(params[:id])`. Rails supports this, by automatically rendering the `_user` partial for each/this object. However Brakeman gives a false warning for this, because it thinks user input is used in determining the path of the partial. Unfortunately this isn't fixed by https://github.com/presidentbeef/brakeman/pull/1578 (I tried), so I will create a separate issue for that.

**Comment by dkniffin** [comment]
@kreintjes Thanks for the heads up. Unfortunately, I'm not quite sure how to reproduce this on my local machine right now. I originally saw it in CI. So, I can't verify whether `main` fixes the issue or not. :/

**Comment by bradparker** [comment]
I've just upgraded to [5.1.1](https://github.com/presidentbeef/brakeman/releases/tag/v5.1.1) which has removed all of our ViewComponent-related false-positives.

**Comment by bradparker** [comment]
@dkniffin did you want to try upgrading to 5.1.1 to see if it resolves your issue?

**Comment by dkniffin** [comment]
@bradparker confirmed, that fixed the issue 👍
