### ISSUE TITLE
Add Ability to Snooze Brakeman Failures

### ISSUE THREAD

**Issue by RTBear** [presidentbeef/brakeman#1696]
Consider the following potentially common situation (I'm currently in this situation): You work at a reasonably large company (multiple devs working in the same repo). At any given moment, there are several feature branches making it through your QA/release process. Suddenly, Brakeman starts causing your pipelines to fail because your Rails version is going to hit end-of-life in a few months. You have two options:
    1. Stop your entire QA/release process while you update your Rails version.
    2. Set `skip_check` for end-of-life, so you don't have to stop your entire release train, and try real hard to remember to turn it back on once you update Rails.

Both of the above options are not great. This type of situation could occur for more than just a Rails version. Nevertheless, there are many valid reasons for not wanting to address a Brakeman failure RIGHT NOW, but also not wanting to forget to address it in the future.

I would like to propose a third solution:
    3. Set a `deadline` option (or sub-option), that will cause Brakeman to throw an error after a given deadline, essentially letting you snooze Brakeman issues. This could be done in a similar way to `skip-checks`, maybe something like `snooze-checks`?

_Edited for clarity_

**Comment by presidentbeef** [comment]
Since the EOL checks are the only time-dependent checks, I'm not inclined to include this kind of feature. Also, where would you store the time information..?

Besides, there is a fourth option which already gives you what you want:

* Open a ticket in your bug tracking system to upgrade the dependency.
* Ignore the warning via `--interactive-ignore` and a `config/brakeman.ignore` file.
* In a month there will be a new warning because the confidence/severity level goes up as the EOL date approaches.
