### ISSUE TITLE
False positive about XSS from "models"

### ISSUE THREAD

**Issue by oliverklee** [presidentbeef/brakeman#597]
In our project, we have a facade class app/models/facades/admin_dashboard. This class acts as a facade for some model statistics (all integers) which we would like to show in the admin dashboard view, allowing us to pass only one object into the view instead of 10 or so variables. The class does not inherit from ActiveRecord::Base.

A typical method from the class looks like this:

```
    ##
    # Returns the total number of users in the database.
    #
    # @return [Integer] the total number of users
    #
    def user_count
      @counts[:user]
    end
```

(@counts is filled in the initialize method).

We use the admin_dashboard instance like this in the view:

```
        != t 'views.admin.statisticsText1Html',
          users: number_with_delimiter(@dashboard.user_count,
            delimiter: t('views.thousandsSeparator')),
```

When I scan our code using brakeman -z -4, we get these warnings:

```
+-------------------+-------+
| Scanned/Reported  | Total |
+-------------------+-------+
| Controllers       | 14    |
| Models            | 24    |
| Templates         | 62    |
| Errors            | 0     |
| Security Warnings | 3 (0) |
+-------------------+-------+

+----------------------+-------+
| Warning Type         | Total |
+----------------------+-------+
| Cross Site Scripting | 3     |
+----------------------+-------+


View Warnings:

+------------+---------------------------------------------+----------------------+------------------------------------------------------------------------->>
| Confidence | Template                                    | Warning Type         | Message                                                                 >>
+------------+---------------------------------------------+----------------------+------------------------------------------------------------------------->>
| Weak       | admin/dashboard (AdminController#dashboard) | Cross Site Scripting | Unescaped model attribute near line 181: t("views.admin.statisticsText1H>>
| Weak       | admin/dashboard (AdminController#dashboard) | Cross Site Scripting | Unescaped model attribute near line 192: t("views.admin.statisticsText2H>>
| Weak       | admin/dashboard (AdminController#dashboard) | Cross Site Scripting | Unescaped model attribute near line 199: t("views.admin.statisticsText3H>>
+------------+---------------------------------------------+----------------------+------------------------------------------------------------------------->>
```

**Comment by oliverklee** [comment]
I'm not quite sure whether this is a bug (as the facade does not inherit ActiveRecord), or whether the best way to solve this would be that we move the facade class out of the models directory.

**Comment by presidentbeef** [comment]
Hi Oliver,

First of all, having only three weak false positives is pretty good :)

Currently Brakeman does not check models to see if they inherit from ActiveRecord, it assumes anything in the `models/` directory is potentially dangerous. I think this may actually be the right thing, because some applications use other database adapters and libraries.

Does this class have any superclasses or include any modules? Maybe one thing we could do is treat a class that is just a Ruby object as a library instead.

For now, you could:

* Use `--skip-files models/your_facade.rb` to skip the facade file entirely
* Use `--ignore-model-output` to not warn on model output in views at all
* Use `-I` to ignore these specific warnings
* Use `-w2` to ignore weak warnings
* Move the file to `lib/` like you said
