### ISSUE TITLE
ARel query false positive in 3.0.0

### ISSUE THREAD

**Issue by phene** [presidentbeef/brakeman#604]
This code, which is an entirely self-contained ARel query, is falsely detected as SQL Injection:

```ruby
group_recipient = GroupRecipient.joins(:group).where(GroupRecipient.arel_table[:message_id].eq Message.arel_table[:id])
group_with_special_property = group_recipient.where(:groups => { :private => false, :special_property => true })
Message.where(group_recipient.exists.not.or(group_with_special_property.exists))
```

Specifically, the `group_recipient.exists` and `group_with_special_property.exists` being used in the 3rd line is being marked.

**Comment by presidentbeef** [comment]
Hi Geoffrey,

Thank you for reporting this issue. My battle against ARel false positives continues...

**Comment by darrenterhune** [comment]
Sorry @presidentbeef but I've found another... damn arel! This is also a self contained query and raises a false positive:
        User.select('users.id').joins(User.joins(:deal_purchases).join_sources).where(DealPurchase.arel_table[:created_at].gt(last_activity)).group('users.id')

Specifically Arel::SelectManager's `join_sources`. If I use `joins('INNER JOIN deal_purchases ON deal_purchases.vendor_id = users.id')` it doesn't raise.

**Comment by phene** [comment]
The latest version 3.0.2 just created several new ARel false-positives. These are starting to get expensive and risky to manage.

```ruby
GroupRecipient.joins(:group).where(GroupRecipient.arel_table[:message_id].eq arel_table[:id])
```

```ruby
  scope :sorted_by, ->(field, asc) {
    asc = ['desc', 'asc'].include?(asc) ? asc : 'asc'
    ordering = if field == 'extension'
      "substring_index(#{table_name}.data_file_name, '.', -1) #{asc}"
    elsif SORTABLE_COLUMNS.include?(field)
      { field.to_sym => asc.to_sym }
    end
    order(ordering)
  }
```

**Comment by presidentbeef** [comment]
Hi Geoffrey,

Sorry for the trouble.

I can only guess without the warning messages, but I can't reproduce a warning from the first bit of code. Is it used inside another query?

The reason the second warning came up with the new release is because `scope` calls like this weren't being processed correctly. I don't think it has anything to do with ARel, just the complexity of the input to `order` is hard to process.

**Comment by phene** [comment]
It is used inside multiple other queries which are getting flagged.

**Comment by presidentbeef** [comment]
Actually I think I can fix the ordering one, too.

**Comment by fschwahn** [comment]
Hi,
I'll just pile on here I guess. The following creates a false positive:

```ruby
scope :by_email, ->(email) { where(self.arel_table[:email].matches(email.strip)) }
```

I guess adding `:matches` here:
https://github.com/presidentbeef/brakeman/blob/c1e2e22939b136e5be38e9470f90046ae889c6cf/lib/brakeman/checks/check_sql.rb#L588

fixes the issue.

**Comment by presidentbeef** [comment]
@fschwahn I can't reproduce this issue. Please open a separate issue to discuss, since this one is already closed. Please include the warning itself as well and make sure you are using the latest version of Brakeman. Thanks.

**Comment by fschwahn** [comment]
@presidentbeef I'm sorry, the issue is an entirely different one. I'm using a shortcut for `arel_table` which allows me to write `User[:email]` instead of `User.arel_table[:email]`, or in the example above `self[:email]` instead of `self.arel_table[:email]`. If I use the normal `arel_table`-syntax no false positive is found, so the problem is the shortcut I'm using. I understand that it's out of scope to support such cases.

Again, sorry for not verifying the problem properly.

**Comment by presidentbeef** [comment]
@fschwahn no worries. And it is unlikely your use case will be supported, sorry.
