### ISSUE TITLE
Relax dependency for ruby_parser

### ISSUE THREAD

**Issue by McRip** [presidentbeef/brakeman#618]
Is it possible to relax the dependency for ruby_parser to ~> 3.6.0. It conflicts with some of my other installed gems. 

Thanks in advance.

**Comment by presidentbeef** [comment]
Hi Moritz,

That's not relaxing a dependency, that's upgrading :)

Unfortunately, due to a change in 3.6.0 (ironically, that I requested), line numbers for HAML templates are very wrong (https://github.com/seattlerb/ruby_parser/pull/157). Without further work on the Brakeman side (or fixing the issue in ruby_parser), I can't change this dependency. This is on my list of things to do, but I'm not sure when it will happen.

My only suggestion at this time is to not put Brakeman in Gemfiles, since its dependencies are not related to any other dependencies. You are welcome to read more of my agonizing in #609 and #602.

**Comment by McRip** [comment]
Hey @presidentbeef ,

thank you very much for your answer and for this comprehensive explanation of the problem!
I will keep an eye on the developments and i am really looking forward to use brakeman very soon.

Cheers
Moritz
