### ISSUE TITLE
gems.locked vs Gemfile.lock

### ISSUE THREAD

**Issue by jlecour** [presidentbeef/brakeman#704]
Hi,

In a recent Rails application, I've chosen to use the `gems.rb`/`gems.locked` (supported by Bundler since 1.8.0) pattern instead of `Gemfile`/`Gemfile.lock`.

Brakeman doesn't seem to support it. It doesn't recognizes the Rails version.

I've forked the repo and looked if I could easily add a test case for this, but since there is a dummy Rails app for various combinations, it would require duplicate of many of them to test this correctly.

As an aside, it took me some time to figure out that the weird report that I had was due to an unrecognized Rails version. The report didn't warn me of the absence of a `Gemfile.lock` file.
Maybe, the `process_gems` method could print a warning if no such file is found.

Anyway, it's my first time using Brakeman. I've known about it since a long time, but the recent RubyRogues episodes was the final push I needed to give it a try.
t looks like a great project. Thanks a lot for building/maintaining it.

**Comment by presidentbeef** [comment]
Hi Jérémy,

Sorry for the trouble. Since it looks like `gems.rb`/`gems.locked` are just new names, it should be no problem to support them.

What version does Brakeman report for your application? Just `Unknown`? It should at least be able to guess Rails 3 or 4. Brakeman started before Gemfiles were commonplace, so a lack of one isn't immediate cause for a warning, but perhaps if it can't determine anything it should show a warning.

In the meantime, you can use the `-3` or `-4` options to force Brakeman to treat the application as a Rails 3 or 4 application.

**Comment by jlecour** [comment]
The Rails versions is `unknown`.

It works perfectly with the `-4` flag.

Thanks.
