### ISSUE TITLE
Unchecked Mass Assignment

### ISSUE THREAD

**Issue by RobertMaloney** [presidentbeef/brakeman#707]
There were some mass assignments, notably detailed by #223, that are not checked now, and were not included in the PR that closed that issue. Particularly, `attributes=` would be quite useful. That might actually be the only one.

**Comment by presidentbeef** [comment]
Hi Robert,

Can you be more specific about what code you expect to generate a warning? Note Brakeman doesn't warn about those calls if the application is using strong parameters.

The reason `attributes=` isn't part of the pull request #234 is because it was already being checked ([code here](https://github.com/presidentbeef/brakeman/blob/dfcd7fdb1ade474d0c0db9fd97a434ea19bb7337/lib/brakeman/checks/check_mass_assignment.rb#L33-L34)).

**Comment by presidentbeef** [comment]
Closing due to lack of response and because I can't reproduce. Brakeman won't warn on every mass assignment call, just those that appear to have user-controllable input.
