### ISSUE TITLE
False Positive - Unsafe model attribute in link_to href

### ISSUE THREAD

**Issue by sakthivelsekar33** [presidentbeef/brakeman#772]
I have the following helper method
```
module PostsHelper
  def path_to_edit_post(post)
    "/posts/#{post.id}/edit"
  end
end
```

In my views 
```
<%= link_to 'Edit', sanitize(path_to_edit_post(@post)) %>
```

### Brakeman Output:
```
Cross Site Scripting | Unsafe model attribute in link_to href
```
As I have sanitized the url and its parameters, this should not be warning against link_to helper. 

There is no warnings if I refactor it this way
```
<%= link_to 'Edit', "/posts/#{post.id}/edit" %>
```
Please let me know if I'm missing anything. Checkout this repo https://github.com/sakthivelsekar33/brakeman-test for the complete app.

**Comment by presidentbeef** [comment]
Hi Sakthivel,

`sanitize` will not help in this case, because it does not protect against the URL beginning with `javascript:`.

However, your code is safe because your helper method interpolates the ID in the middle of the string. Besides, the post ID will be an integer which is safe.

Unfortunately, at this time Brakeman does not look into helper methods to see what they return (although [Brakeman Pro](https://brakemanpro.com/) does...) so it can't tell that you are doing something safe.

That being said, the Rails way to do this would be to call `edit_post_path(post)` to get the path. Brakeman should not warn if you do it this way.
