### ISSUE TITLE
Implement a 'brakeman is on the latest version' check

### ISSUE THREAD

**Issue by grosser** [presidentbeef/brakeman#968]
with `--ensure-latest` should fail when brakeman is outdated and I might be missing some shiny new detections ... basically what https://rubygems.org/gems/brakecheck does ... but would be nice to integrate this since it is super-duper simple ...

/cc @apanzerj

**Comment by presidentbeef** [comment]
You really like failing builds, huh?

I implemented this a long time (years) ago but didn't merge it because it can't be on by default (since it does network calls) but if it's not on by default it limits usefulness.

**Comment by grosser** [comment]
I like to be warned about security issues ... usually new brakeman releases show a few new finding :)

**Comment by apanzerj** [comment]
Breaking the build is a good way to get people to maintain the community of the project. Several teams contribute to the same project so nobody really "owns" the project as a whole. Breaking the build means the very next person working on that project will take the initiative to update the dependency rather than let somebody else do it.

**Comment by presidentbeef** [comment]
Sorry, I meant to also mention I'm happy to add this option.

My comment about breaking builds was due to @grosser making a number of requests for new options to fail builds for different reasons.

**Comment by apanzerj** [comment]
Ahhh. He likes breaking things 😀

**Comment by presidentbeef** [comment]
Added in #974
